[workspace]
members = [
    "src/canisters/dao",
    "src/canisters/hiving",
    "src/canisters/hiving_pool",
    "src/canisters/nft",
    "src/canisters/token",
    "src/shared/abstractions",
    "src/shared/canister_runtime",
    "tst/scenarios",
]
resolver = "2"
