[package]
name = "token_ledger"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10.13"
ciborium = "0.2.2"
ic-cdk = "0.18.0"
ic-stable-structures = "0.6.8"
icrc-ledger-types = "0.1.8"
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = "1.0.219"