[package]
name = "canister-runtime"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = "0.1.88"
candid = "0.10.14"
ic-cdk = "0.18.5"
serde = { version = "=1.0.219", features = ["derive"] }
abstractions = { path = "../abstractions" }
